const CONFIG = {
    DEBUG: { LIMIT: null },
    DATA: { FILE_SIZE: 23561391 },
    FILES: {
        MANIFEST: "overseas_entities_data_info.txt",
        PROPERTIES_DEFAULT: "overseas_entities_properties.msgpack",
        PROPRIETORS_DEFAULT: "overseas_entities_proprietors.msgpack",
    },
    CACHE: {
        VERSION_KEY: "oe-data-version-v2",
        PROPERTIES_KEY: "oe-properties-v2",
        PROPRIETORS_KEY: "oe-proprietors-v2",
    },
    MAP: {
        ATTRIBUTION_HTML: "Map tiles: &copy; OpenStreetMap contributors &copy; CARTO.",
        PROPERTY_FLY_TO_ZOOM: 17,
        DEFAULT_CENTER: [52.234528, -0.999756],
        DEFAULT_ZOOM: { DESKTOP: 7, MOBILE: 6 },
        INITIAL_VIEW: { CENTER: [54, -2], ZOOM: 2 },
        MIN_ZOOM: 2,
        WORLD_BOUNDS: {
            SOUTH_WEST: [-90, -180],
            NORTH_EAST: [90, 180],
        },
        TILE_LAYER_URL: "https://{s}.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}{r}.png",
        TILE_LAYER_OPTIONS: { worldCopyJump: true, noWrap: false },
        PANE_ZINDEX: {
            PROPERTY_HIGHLIGHT: 650,
            NO_DATA: 650,
        },
        NO_DATA_MARKERS: [
            { KEY: "scotland", LAT: 56.599439013318005, LON: -4.22718327285142 },
            { KEY: "northern_ireland", LAT: 54.71511897854079, LON: -6.86011631976435 },
        ],
        FLY_DURATION: {
            REDUCED_MOTION: 0.2,
            MOBILE: 1.2,
            DESKTOP: 1.6,
        },
    },
    COLORS: {
        CATEGORY: {
            GREEN: "#6ACC64",
            ORANGE: "#DD8452",
            RED: "#C44E52",
            GREY: "#939699",
            PURPLE: "#563d7c",
            BLUE: "#4C72B0",
        },
    },
    STORAGE: {
        IOS_ADD_TO_HOME_PROMPT_KEY: "oeMapIosAddToHomePromptShown",
        TUTORIAL_COOKIE_KEY: "tutorialSeen_intro",
    },
    PROPERTY_TYPES: {
        CODES: new Set(["D", "S", "T", "F", "O"]),
        DEFAULT: "all",
    },
    UI: {
        MOBILE_BREAKPOINT: 992,
        TOP_VALUABLE_PROPERTIES_LIMIT: 10000,
    },
    PANEL_LAYOUT: {
        MOBILE: {
            LANDSCAPE: { WIDTH: "40vw", LEFT: "30vw" },
            PORTRAIT: { WIDTH: "90vw", LEFT: "5vw" },
            MAX_HEIGHT: "75vh",
            TOP: "60px",
            TRANSFORM: "none",
        },
        DESKTOP: {
            WIDTH: "320px",
            MAX_HEIGHT: "80vh",
            TRANSFORM: "none",
            PADDING_PX: 15,
        },
    },
    INTERACTION: {
        SHARE_MAX_LINKS: 9,
        SEARCH_MAX_RESULTS: 100,
        DEBOUNCE_MS: {
            ENTITY_SEARCH: 300,
            PLACE_SEARCH: 350,
        },
    },
    CLUSTERS: {
        OPTIONS: {
            showCoverageOnHover: false,
            chunkedLoading: true,
            chunkInterval: 200,
            chunkDelay: 50,
        },
        ICON_SIZE_BREAKPOINTS: {
            SMALL_MAX: 100,
            MEDIUM_MAX: 1000,
        },
        ICON_SIZE_PIXELS: {
            SMALL: 40,
            MEDIUM: 50,
            LARGE: 60,
        },
    },
    ZOOM_LEVELS: {
        TYPE_CAPS: {
            continent: 4,
            ocean: 4,
            sea: 5,
            archipelago: 7,
            country: 6,
            state: 8,
            province: 8,
            region: 8,
            state_district: 9,
            district: 10,
            county: 10,
            municipality: 11,
            borough: 12,
            city: 12,
            city_district: 13,
            town: 13,
            village: 14,
            hamlet: 15,
            suburb: 15,
            neighbourhood: 16,
            neighborhood: 16,
            locality: 16,
            quarter: 15,
            postcode: 16,
            postal_code: 16,
            road: 17,
            street: 17,
            residential: 17,
            track: 17,
            footway: 17,
            path: 17,
            service: 17,
            motorway: 15,
            trunk: 15,
            primary: 15,
            secondary: 16,
            tertiary: 16,
            airport: 13,
            aerodrome: 13,
            railway: 16,
            station: 16,
            platform: 17,
            bus_stop: 17,
            tram_stop: 17,
            industrial: 17,
            commercial: 17,
            retail: 17,
            farm: 16,
            park: 14,
            forest: 12,
            island: 10,
            lake: 10,
            harbour: 14,
            school: 17,
            university: 17,
            hospital: 17,
            building: 18,
            house: 18,
            apartments: 18,
            detached: 18,
            bungalow: 18,
            address: 18,
            yes: 17
        },
        CLASS_CAPS: {
            boundary: 9,
            place: 12,
            natural: 10,
            landuse: 13,
            leisure: 14,
            waterway: 12,
            aeroway: 13,
            highway: 17,
            railway: 16,
            amenity: 17,
            tourism: 16,
            shop: 17,
            building: 18,
            man_made: 17,
            office: 17
        },
        PLACE_RESULT: {
            FALLBACK: 16,
            ABSOLUTE_MIN: 2,
            ABSOLUTE_MAX: 18,
        },
    },
    STYLES: {
        PROPERTY_HIGHLIGHT: {
            RADIUS: 24,
            COLOR: "#d12b2b",
            WEIGHT: 4,
        },
        LINK_LINES: {
            PROPERTY_TO_PROPRIETOR: {
                WITH_BOS_COLOR: "black",
                WITHOUT_BOS_COLOR: "red",
                WEIGHT: 3,
            },
            PROPRIETOR_TO_BO: {
                DEFAULT_COLOR: "green",
                SUSPECT_COLOR: "red",
                WEIGHT: 3,
                DASH_ARRAY: "5, 10",
            },
        },
    },
    URLS: {
        LAND_REGISTRY_SEARCH: "https://search-property-information.service.gov.uk/search/search-by-title-number",
        NOMINATIM_SEARCH: "https://nominatim.openstreetmap.org/search",
        MATERIAL_SYMBOLS_BASE: "https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined",
    },
    ICONS: {
        MATERIAL_SYMBOLS_STATIC: [
            "cancel",
            "link",
            "refresh",
            "search",
            "factory",
            "download",
            "add",
            "map",
            "remove",
            "menu",
            "apartment",
            "article",
            "group",
            "search",
            "rocket",
            "currency_pound",
            "draw",
            "globe",
            "attach_email",
            "help_outline",
            "link",
            "g_mobiledata_badge",
            "chevron_left",
            "chevron_right",
            "close",
            "person",
            "my_location"
        ],
    },
    BO_KIND: {
        ID_TO_LONG: {
            "1": "individual-beneficial-owner",
            "2": "corporate-entity-beneficial-owner",
            "3": "legal-person-beneficial-owner",
            "4": "super-secure-beneficial-owner",
            "5": "super-secure-person-with-significant-control",
            "6": "corporate-entity-person-with-significant-control",
        },
    },
};
